stages:
    - test
    - compile
    - release

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - dist/

before_script:
    - npm install --save-dev

test_job:
    stage: test
    script:
      - npm run test
    tags:
      - master

build_job:
    stage: compile
    script:
      - npm run build
    tags:
      - master


test_ci_push:
  stage: release
  tags:
    - master
  allow_failure: true
  script:
    - npm run build
    - git config --global user.name "rebot"
    - git config --global user.email "rebot@mchz.com.cn"
    - git add --all
    - git commit -m "GitLab Runner Push"
    - git push http://rebot:XpyMqPEHPw7ojAtimwEE@gitlab/mcf/module.git HEAD:master
    - echo "push code success!"
